[tool.poetry]
name = "hexlet-flask-example"
version = "0.1.0"
description = ""
authors = ["vitallcore <vitaslipknot@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
